version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
    container_name: mongodb

  backend:
    build: ./server/
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    container_name: server
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/server/

  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend
    container_name: frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/:/frontend/

volumes:
  mongodb_data:
    driver: local
