version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: CMarghin
      MONGO_INITDB_ROOT_PASSWORD: cmarghin123
    container_name: mongodb
  backend:
    build: ./server/
    ports:
      - 5000:5000
    container_name: server
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/server/
